// app/(marketing)/layout.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "FolioSync — AI Portfolio Generator | Connect. Generate. Publish.",
  description:
    "Connect your GitHub, LinkedIn, Twitter & more. AI scrapes everything and generates a beautiful, always-updated portfolio in seconds.",
  openGraph: {
    title: "FolioSync — AI Portfolio Generator",
    description:
      "Your entire online presence. One stunning portfolio. Auto-generated by AI.",
    type: "website",
  },
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}



